export const displayNames = {
  Nwppc: 'Conductors per Slot',
  Wwire: 'Conductor Diameter',
  Nlayer: 'Layers',
  Ntcoil: 'Number of Turns',
  Wins_cond: '​Insulation Conductivity',
  Wins_wire: '​Insualtion Thickness',
  ConductorMaterial: '​Winding Material',
  InsulationMaterial: 'Insulation Material',
  Hwire: 'H Wire',
  Nwppc_rad: 'Nwppc Rad',
  Nwppc_tan: 'Nwppc Tan',
  Wins_coil: 'Wins Coil',
  Npcp: 'Circuits per Phase',
  Material: 'Material',
  CoreLength: 'Core Length',
  PackingFactor: 'Packing Factor',
  ExternalRadius: 'External Radius',
  InternalRadius: 'Internal Radius',
  ResinConductivity: 'Resin Conductivity',
  NDECopperOverhang: 'NDE Copper Overhang',
  DECopperOverhang: 'DE Copper Overhang',
  FrameLength: 'Frame Length',
  Barrelgap: 'Barrel Gap',
  NBar: 'NBar',
  WidthBar: 'Width Bar',
  W0: 'Slot Opening',
  H0: 'Opening Depth',
  W1: 'Slot Width',
  W1_1: 'Slot Width Top',
  H1: 'Wedge Height',
  W2: 'Slot Width Bottom',
  H2: 'Winding Depth',
  R1: 'Corner Radius',
  W3: 'Tooth Width',
  W4: 'Tooth Width Bottom',
  Zs: 'Number of Slots',
  H3_rotor: 'Winding Gap 1',
  H4_rotor: 'Winding Gap 2',
  W1_rotor: 'Shoe Width',
  W2_rotor: 'Pole Width',
  W3_rotor: 'Winding Gap 3',
  H1_rotor: 'Shoe Depth',
  H2_rotor: 'Pole Cutout Height',
  R1_rotor: 'Pole Radius',
  Zs_rotor: 'Number of Poles',
};