// Alert Action Types
export const SET_HIDE_ALERT = 'SET_HIDE_ALERT';
export const SET_SHOW_ALERT = 'SET_SHOW_ALERT';

// Project Action Types
export const SET_PROJECT_LOADING = 'SET_PROJECT_LOADING';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';

// Machine Action Types
export const SET_MACHINE_LOADING = 'SET_MACHINE_LOADING';
export const NEW_MACHINE_CREATED = 'NEW_MACHINE_CREATED';
export const SUCCESS_GETTING_MACHINES = 'SUCCESS_GETTING_MACHINES';
export const LOAD_MACHINE = 'LOAD_MACHINE';
export const SET_MATERIALS = 'SET_MATERIALS';

// Stator Action Types
export const INIT_STATOR_PARAMS = 'INIT_STATOR_PARAMS';
export const SET_DISABLE_STATOR_SAVE_BUTTON = 'SET_DISABLE_STATOR_SAVE_BUTTON';
export const SET_STATOR_LAMINATION_DATA = 'SET_STATOR_LAMINATION_DATA';
export const SET_STATOR_LAMINATION_PARAM = 'SET_STATOR_LAMINATION_PARAM';
export const SET_STATOR_LAMINATION_TYPE = 'SET_STATOR_LAMINATION_TYPE';
export const SET_STATOR_SLOT_DATA = 'SET_STATOR_SLOT_DATA';
export const SET_STATOR_SLOT_PARAM = 'SET_STATOR_SLOT_PARAM';
export const SET_STATOR_SLOT_TYPE = 'SET_STATOR_SLOT_TYPE';
export const SET_STATOR_SLOT_IMAGE_URL = 'SET_STATOR_SLOT_IMAGE_URL';
export const SET_STATOR_CONDUCTOR_DATA = 'SET_STATOR_CONDUCTOR_DATA';
export const SET_STATOR_CONDUCTOR_PARAM = 'SET_STATOR_CONDUCTOR_PARAM';
export const SET_STATOR_CONDUCTOR_TYPE = 'SET_STATOR_CONDUCTOR_TYPE';
export const SET_STATOR_CONDUCTOR_TYPES = 'SET_STATOR_CONDUCTOR_TYPES';
export const SET_STATOR_CONDUCTOR_IMAGE_URL = 'SET_STATOR_CONDUCTOR_IMAGE_URL';
export const SET_STATOR_MAIN_IMAGE_URL = 'SET_STATOR_MAIN_IMAGE_URL';
export const SET_STATOR_WINDING_TYPE = 'SET_STATOR_WINDING_TYPE';
export const SET_STATOR_WINDING_DATA = 'SET_STATOR_WINDING_DATA';
export const SET_STATOR_WINDING_PARAM = 'SET_STATOR_WINDING_PARAM';
export const SET_STATOR_WINDING_IMAGE_URL = 'SET_STATOR_WINDING_IMAGE_URL';
export const SET_STATOR_MATERIAL_DICT = 'SET_STATOR_MATERIAL_DICT';
export const SET_STATOR_WINDING_MATERIAL_DICT = 'SET_STATOR_WINDING_MATERIAL_DICT';
export const SET_STATOR_INSULATION_MATERIAL_DICT = 'SET_STATOR_INSULATION_MATERIAL_DICT';
export const SET_STATOR_IMPREGNATION_MATERIAL_DICT = 'SET_STATOR_IMPREGNATION_MATERIAL_DICT';
export const SET_STATOR_WALLINSULATION_MATERIAL_DICT = 'SET_STATOR_WALLINSULATION_MATERIAL_DICT';
export const SET_STATOR_WEDGE_MATERIAL_DICT = 'SET_STATOR_WEDGE_MATERIAL_DICT';
export const SET_STATOR_SEPARATOR_MATERIAL_DICT = 'SET_STATOR_SEPARATOR_MATERIAL_DICT';
export const SET_STATOR_COILINSULATION_MATERIAL_DICT = 'SET_STATOR_COILINSULATION_MATERIAL_DICT';
export const SET_STATOR_TOPSPACER_MATERIAL_DICT = 'SET_STATOR_TOPSPACER_MATERIAL_DICT';
export const SET_STATOR_BOTTOMSPACER_MATERIAL_DICT = 'SET_STATOR_BOTTOMSPACER_MATERIAL_DICT';
export const SET_STATOR_LEFTSPACER_MATERIAL_DICT = 'SET_STATOR_LEFTSPACER_MATERIAL_DICT';
export const SET_STATOR_RIGHTSPACER_MATERIAL_DICT = 'SET_STATOR_RIGHTSPACER_MATERIAL_DICT';
export const SET_STATOR_SLOT_MATERIAL_DICT = 'SET_STATOR_SLOT_MATERIAL_DICT';

// Rotor Action Types
export const INIT_ROTOR_PARAMS = 'INIT_ROTOR_PARAMS';
export const SET_DISABLE_ROTOR_SAVE_BUTTON = 'SET_DISABLE_ROTOR_SAVE_BUTTON';
export const SET_ROTOR_LAMINATION_DATA = 'SET_ROTOR_LAMINATION_DATA';
export const SET_ROTOR_LAMINATION_PARAM = 'SET_ROTOR_LAMINATION_PARAM';
export const SET_ROTOR_LAMINATION_TYPE = 'SET_ROTOR_LAMINATION_TYPE';
export const SET_ROTOR_SLOT_DATA = 'SET_ROTOR_SLOT_DATA';
export const SET_ROTOR_SLOT_PARAM = 'SET_ROTOR_SLOT_PARAM';
export const SET_ROTOR_SLOT_TYPE = 'SET_ROTOR_SLOT_TYPE';
export const SET_ROTOR_SLOT_IMAGE_URL = 'SET_ROTOR_SLOT_IMAGE_URL';
export const SET_ROTOR_CONDUCTOR_DATA = 'SET_ROTOR_CONDUCTOR_DATA';
export const SET_ROTOR_CONDUCTOR_PARAM = 'SET_ROTOR_CONDUCTOR_PARAM';
export const SET_ROTOR_CONDUCTOR_TYPE = 'SET_ROTOR_CONDUCTOR_TYPE';
export const SET_ROTOR_CONDUCTOR_IMAGE_URL = 'SET_ROTOR_CONDUCTOR_IMAGE_URL';
export const SET_ROTOR_HOLE_DATA = 'SET_ROTOR_HOLE_DATA';
export const SET_ROTOR_HOLE_PARAM = 'SET_ROTOR_HOLE_PARAM';
export const SET_ROTOR_HOLE_TYPE = 'SET_ROTOR_HOLE_TYPE';
export const SET_ROTOR_HOLE_IMAGE_URL = 'SET_ROTOR_HOLE_IMAGE_URL';
export const SET_ROTOR_MAIN_IMAGE_URL = 'SET_ROTOR_MAIN_IMAGE_URL';
export const SET_ROTOR_WINDING_DATA = 'SET_ROTOR_WINDING_DATA';
export const SET_ROTOR_WINDING_PARAM = 'SET_ROTOR_WINDING_PARAM';
export const SET_ROTOR_WINDING_TYPE = 'SET_ROTOR_WINDING_TYPE';
export const SET_ROTOR_CONDUCTOR_TYPES = 'SET_ROTOR_CONDUCTOR_TYPES';
export const SET_ROTOR_WINDING_IMAGE_URL = 'SET_ROTOR_WINDING_IMAGE_URL';
export const SET_ROTOR_MATERIAL_DICT = 'SET_ROTOR_MATERIAL_DICT';
export const SET_ROTOR_WINDING_MATERIAL_DICT = 'SET_ROTOR_WINDING_MATERIAL_DICT';
export const SET_ROTOR_INSULATION_MATERIAL_DICT = 'SET_ROTOR_INSULATION_MATERIAL_DICT';
export const SET_ROTOR_WALLINSULATION_MATERIAL_DICT = 'SET_ROTOR_WALLINSULATION_MATERIAL_DICT';
export const SET_ROTOR_IMPREGNATION_MATERIAL_DICT = 'SET_ROTOR_IMPREGNATION_MATERIAL_DICT';
export const SET_ROTOR_HOLE_MATERIAL_DICT = 'SET_ROTOR_HOLE_MATERIAL_DICT';

// Housing Action Types
export const INIT_HOUSING_PARAMS = 'INIT_HOUSING_PARAMS';
export const SET_DISABLE_HOUSING_SAVE_BUTTON = 'SET_DISABLE_HOUSING_SAVE_BUTTON';
export const SET_HOUSING_DATA = 'SET_HOUSING_DATA';
export const SET_HOUSING_PARAM = 'SET_HOUSING_PARAM';
export const SET_HOUSING_TYPE = 'SET_HOUSING_TYPE';
export const SET_HOUSING_IMAGE_URL = 'SET_HOUSING_IMAGE_URL';
export const SET_HOUSING_MAIN_IMAGE_URL = 'SET_HOUSING_MAIN_IMAGE_URL';
export const SET_HOUSING_MATERIAL_DICT = 'SET_HOUSING_MATERIAL_DICT';

// Results Action Types
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';

// Loss Action Types
export const INIT_LOSS_PARAMS = 'INIT_LOSS_PARAMS';
export const SET_LOSS_DATA = 'SET_LOSS_DATA';
export const SET_LOSS_PARAM = 'SET_LOSS_PARAM';
export const SET_LOSS_TYPE = 'SET_LOSS_TYPE';
export const SET_LOSS_MAIN_IMAGE_URL = 'SET_LOSS_MAIN_IMAGE_URL';

// Cooling Action Types
export const INIT_COOLING_PARAMS = 'INIT_COOLING_PARAMS';
export const SET_COOLING_FLOW_DATA = 'SET_COOLING_FLOW_DATA';
export const SET_COOLING_HTC = 'SET_COOLING_HTC';
export const SET_COOLING_PARAM = 'SET_COOLING_PARAM';
export const SET_COOLING_TYPE = 'SET_COOLING_TYPE';
export const SET_COOLING_IMAGE_URL = 'SET_COOLING_IMAGE_URL';
export const SET_HTC_DATA = 'SET_HTC_DATA';
export const SET_COOLING_ROTOR_TYPE = 'SET_COOLING_ROTOR_TYPE';
export const SET_COOLING_HOUSING_TYPE = 'SET_COOLING_HOUSING_TYPE';
export const SET_COOLING_F_ROTOR_TYPE = 'SET_COOLING_F_ROTOR_TYPE';
export const SET_COOLING_F_HOUSING_TYPE = 'SET_COOLING_F_HOUSING_TYPE';
export const SET_WATER_CHECKED = 'SET_WATER_CHECKED';

// LPTN Action Types
export const SET_LPTN_SOLVE_TASK_ID = 'SET_LPTN_SOLVE_TASK_ID';
export const SET_LPTN_RESULT = 'SET_LPTN_RESULT';
